import db from './db.js';

const categories = [
  {
    name: 'Mode & Vêtements',
    slug: 'mode-vetements',
    description: 'Découvrez notre collection de vêtements tendance et élégants',
    image_url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&h=500&q=80',
    display_order: 1,
  },
  {
    name: 'Bijoux & Accessoires',
    slug: 'bijoux-accessoires',
    description: 'Des bijoux raffinés pour sublimer chaque tenue',
    image_url: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&h=500&q=80',
    display_order: 2,
  },
  {
    name: 'Beauté & Soins',
    slug: 'beaute-soins',
    description: 'Prenez soin de vous avec nos produits de beauté sélectionnés',
    image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&h=500&q=80',
    display_order: 3,
  },
  {
    name: 'Maison & Décoration',
    slug: 'maison-decoration',
    description: 'Embellissez votre intérieur avec nos pièces décoratives',
    image_url: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=800&h=500&q=80',
    display_order: 4,
  },
  {
    name: 'Sacs & Chaussures',
    slug: 'sacs-chaussures',
    description: 'Sacs à main et chaussures pour compléter votre style',
    image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&h=500&q=80',
    display_order: 5,
  },
  {
    name: 'High-Tech',
    slug: 'high-tech',
    description: 'Gadgets et accessoires technologiques tendance',
    image_url: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&w=800&h=500&q=80',
    display_order: 6,
  },
];

const products = [
  {
    name: 'Robe d\'été florale',
    slug: 'robe-ete-florale',
    description: 'Une robe légère et élégante, parfaite pour les journées ensoleillées. Tissu fluide et imprimé floral délicat.',
    price: 15900,
    compare_price: 22000,
    image_url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'mode-vetements',
    stock: 25,
    featured: 1,
  },
  {
    name: 'Blazer oversize beige',
    slug: 'blazer-oversize-beige',
    description: 'Un blazer oversize en lin mélangé, coupe moderne et décontractée. Idéal pour un look chic au quotidien.',
    price: 24500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'mode-vetements',
    stock: 15,
    featured: 1,
  },
  {
    name: 'Ensemble loungewear satin',
    slug: 'ensemble-loungewear-satin',
    description: 'Ensemble pyjama en satin doux, parfait pour un confort luxueux à la maison.',
    price: 18500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'mode-vetements',
    stock: 20,
    featured: 0,
  },
  {
    name: 'Jean taille haute slim',
    slug: 'jean-taille-haute-slim',
    description: 'Jean slim taille haute en denim stretch, coupe flatteuse et confortable pour toutes les silhouettes.',
    price: 13500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'mode-vetements',
    stock: 30,
    featured: 0,
  },
  {
    name: 'Collier doré perles',
    slug: 'collier-dore-perles',
    description: 'Collier délicat en plaqué or orné de perles d\'eau douce. Un bijou intemporel et raffiné.',
    price: 8900,
    compare_price: 12000,
    image_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'bijoux-accessoires',
    stock: 40,
    featured: 1,
  },
  {
    name: 'Boucles d\'oreilles créoles',
    slug: 'boucles-oreilles-creoles',
    description: 'Créoles en acier inoxydable doré, design épuré et élégant. Résistant à l\'eau.',
    price: 4500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'bijoux-accessoires',
    stock: 50,
    featured: 0,
  },
  {
    name: 'Montre minimaliste rose gold',
    slug: 'montre-minimaliste-rose-gold',
    description: 'Montre femme au design épuré, bracelet en mesh rose gold. Mouvement quartz japonais.',
    price: 16900,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'bijoux-accessoires',
    stock: 12,
    featured: 1,
  },
  {
    name: 'Coffret skincare routine',
    slug: 'coffret-skincare-routine',
    description: 'Coffret complet pour une routine beauté : nettoyant, sérum, crème hydratante et masque.',
    price: 22000,
    compare_price: 32000,
    image_url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'beaute-soins',
    stock: 18,
    featured: 1,
  },
  {
    name: 'Huile de rose musquée bio',
    slug: 'huile-rose-musquee-bio',
    description: 'Huile précieuse 100% bio pour nourrir et régénérer la peau. Anti-âge naturel.',
    price: 7500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'beaute-soins',
    stock: 35,
    featured: 0,
  },
  {
    name: 'Palette maquillage nude',
    slug: 'palette-maquillage-nude',
    description: '12 teintes nude et rosées pour un maquillage naturel ou sophistiqué. Fards hautement pigmentés.',
    price: 11500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'beaute-soins',
    stock: 22,
    featured: 0,
  },
  {
    name: 'Bougie parfumée artisanale',
    slug: 'bougie-parfumee-artisanale',
    description: 'Bougie en cire de soja naturelle parfumée à la fleur de coton. Durée : 45 heures.',
    price: 6500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'maison-decoration',
    stock: 45,
    featured: 1,
  },
  {
    name: 'Vase en céramique blanche',
    slug: 'vase-ceramique-blanche',
    description: 'Vase artisanal en céramique mate, forme organique et épurée. Pièce unique.',
    price: 9800,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'maison-decoration',
    stock: 10,
    featured: 0,
  },
  {
    name: 'Coussin en lin naturel',
    slug: 'coussin-lin-naturel',
    description: 'Housse de coussin en lin lavé, teinte naturelle. 45x45cm. Confort et élégance.',
    price: 5200,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'maison-decoration',
    stock: 30,
    featured: 0,
  },
  {
    name: 'Sac bandoulière cuir camel',
    slug: 'sac-bandouliere-cuir-camel',
    description: 'Sac bandoulière en cuir véritable, teinte camel. Compartiments pratiques et design intemporel.',
    price: 28500,
    compare_price: 35000,
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'sacs-chaussures',
    stock: 8,
    featured: 1,
  },
  {
    name: 'Sandales tressées dorées',
    slug: 'sandales-tressees-dorees',
    description: 'Sandales plates en cuir tressé doré, parfaites pour l\'été. Semelle en cuir souple.',
    price: 12900,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'sacs-chaussures',
    stock: 18,
    featured: 0,
  },
  {
    name: 'Pochette soirée satinée',
    slug: 'pochette-soiree-satinee',
    description: 'Pochette de soirée en satin avec fermoir doré. Compacte et élégante pour vos sorties.',
    price: 9500,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'sacs-chaussures',
    stock: 14,
    featured: 0,
  },
  {
    name: 'Écouteurs sans fil rose gold',
    slug: 'ecouteurs-sans-fil-rose-gold',
    description: 'Écouteurs Bluetooth avec boîtier de charge élégant. Réduction de bruit active. Autonomie 24h.',
    price: 19900,
    compare_price: 25000,
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'high-tech',
    stock: 20,
    featured: 1,
  },
  {
    name: 'Ring light LED professionnel',
    slug: 'ring-light-led-professionnel',
    description: 'Anneau lumineux LED 10 pouces avec trépied réglable. 3 modes d\'éclairage, 10 niveaux.',
    price: 8900,
    compare_price: null,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&h=600&q=80',
    category_slug: 'high-tech',
    stock: 25,
    featured: 0,
  },
];

db.resetAll();

const categoryMap = {};
for (const cat of categories) {
  const inserted = db.insert('categories', {
    name: cat.name,
    slug: cat.slug,
    description: cat.description,
    image_url: cat.image_url,
    display_order: cat.display_order,
  });
  categoryMap[cat.slug] = inserted.id;
}

for (const prod of products) {
  db.insert('products', {
    name: prod.name,
    slug: prod.slug,
    description: prod.description,
    price: prod.price,
    compare_price: prod.compare_price,
    image_url: prod.image_url,
    category_id: categoryMap[prod.category_slug],
    stock: prod.stock,
    featured: prod.featured,
  });
}

console.log(`✨ Base de données remplie : ${categories.length} catégories, ${products.length} produits`);
process.exit(0);
